Repository uni-clouds/unicloud-frontwebapp, pull requests merged in 2022-07, with the labels that each got.

#34 Upkeeps 1
  src/Templates/CustomersList/index.tsx
  src/Templates/Dashboard/index.tsx
  src/Templates/UsersList/InviteList/Header.tsx
  src/components/Dashboard/Cards/CardDefault.tsx
  src/components/Dashboard/Cards/CardListPartners.tsx
  src/components/Elements/Inputs/CnpjField.tsx
  src/components/Elements/Inputs/Input.tsx
  src/components/Elements/Inputs/PhoneInput.tsx
  src/components/Elements/Inputs/TypeInput.tsx
  src/components/Elements/Navigation/NavLinksHelpers.tsx
  src/components/Elements/Navigation/PathActive.tsx
  src/components/Elements/Navigation/types.ts
  src/components/Footer/index.tsx
  src/components/Forms/CreateCustomer/index.tsx
  src/components/Forms/CreateCustomer/validation.ts
  src/components/Forms/DetailsCustomer/index.tsx
  src/components/Forms/DetailsUser/index.tsx
  src/components/Layout/index.tsx
  src/components/Navbar/Sidebar/index.tsx
  src/components/Navbar/Sidebar/types.ts
  src/components/Navbar/Sidebar/variants.ts
  src/components/NotificationsContent/CardNotifications.tsx
  src/components/NotificationsContent/index.tsx
  src/components/Tables/Clients/data.ts
  src/components/Tables/Clients/index.tsx
  src/components/Tables/Customers/CustomTableHead.tsx
  src/components/Tables/Customers/TableToolbar.tsx
  src/components/Tables/Customers/index.tsx
  src/components/Tables/Customers/types.ts
  src/components/Tables/Invites/CustomTableHead.tsx
  src/components/Tables/Invites/TableToolbar.tsx
  src/components/Tables/Invites/index.tsx
  src/components/Tables/Users/CustomTableHead.tsx
  src/components/Tables/Users/TableToolbar.tsx
  src/components/Tables/Users/index.tsx
  src/components/Tables/styles.ts
  src/hooks/useCustomersList.tsx
  src/pages/Placeholder/index.tsx
  src/services/api.ts
Labels: :lady_beetle: bug, :sparkles: New feature, :recycle: Refatoração

#36 switch url backend prod
  src/services/api.ts
Labels: :lady_beetle: bug

#42 ✨ User profile
  src/components/Profile/Activities/index.tsx
  src/components/Profile/InformationDisplay/index.tsx
  src/components/Profile/NavigationItem/index.tsx
  src/components/Profile/PersonalInformation/index.tsx
  src/components/Profile/SafetySettings/index.tsx
  src/components/Profile/index.tsx
  src/components/Profile/types.ts
  src/components/Profile/util.ts
  src/components/Tables/Users/types.ts
  src/pages/UserProfile/index.tsx
  src/routes/index.tsx
Labels: :sparkles: New feature

#45 ♻️ Refactor: tela de login
  src/Templates/Login/index.tsx
  src/components/Elements/Navigation/NavLinkLogin.tsx
  src/components/Elements/Navigation/NavLinksHelpers.tsx
  src/components/Elements/OrganizationLogo/index.tsx
Labels: :recycle: Refatoração

#80 Multilanguage i 72
  locales/combined/en.json
  locales/combined/es.json
  locales/combined/fr.json
  locales/combined/pt.json
  locales/en/common.json
  locales/en/customers-users.json
  locales/en/validation.json
  locales/es/common.json
  locales/es/customers-users.json
  locales/es/pods.json
  locales/es/validation.json
  locales/fr/common.json
  locales/fr/customers-users.json
  locales/fr/pods.json
  locales/fr/validation.json
  locales/pt/common.json
  locales/pt/customers-users.json
  locales/pt/validation.json
  src/Templates/Dashboard/index.tsx
  src/Templates/Dashboard/types.ts
  src/components/Dashboard/Cards/CardDefault.tsx
  src/components/Elements/Inputs/CnpjField.tsx
  src/components/Elements/Inputs/Input.tsx
  src/components/Elements/Inputs/PhoneInput.tsx
  src/components/Elements/Inputs/TypeInput.tsx
  src/components/Elements/LanguageSelector.tsx
  src/components/Footer/index.tsx
  src/components/Forms/CreateCustomer/index.tsx
  src/components/Forms/CreateCustomer/util.ts
  src/components/Forms/CreateCustomer/validation.ts
  src/components/Forms/CreatePod/validation.ts
  src/components/Forms/DetailsUser/validation.ts
  src/components/Forms/InviteUser/validation.ts
  src/components/Forms/Login/validation.ts
  src/components/Forms/RegisterUser/validation.ts
  src/components/LanguageSelector/RenderFlag.tsx
  src/components/LanguageSelector/data.ts
  src/components/LanguageSelector/index.tsx
  src/components/LanguageSelector/types.ts
  src/components/LanguageSelector/util.ts
  src/components/Profile/PersonalInformation/index.tsx
  src/components/Tables/Customers/CustomTableHead.tsx
  src/components/Tables/Customers/data.ts
  src/components/Tables/Customers/index.tsx
  src/components/Tables/Invites/CustomTableHead.tsx
  src/components/Tables/Invites/TableToolbar.tsx
  src/components/Tables/Invites/data.ts
  src/components/Tables/Invites/index.tsx
  src/components/Tables/Users/CustomTableHead.tsx
  src/components/Tables/Users/TableToolbar.tsx
  src/components/Tables/Users/data.ts
  src/components/Tables/Users/index.tsx
  src/i18n/index.ts
Labels: :recycle: Refatoração

#89 Metadata language i81
  index.html
  locales/combined/en.json
  locales/combined/es.json
  locales/combined/fr.json
  locales/combined/pt.json
  locales/en/common.json
  locales/en/validation.json
  locales/es/common.json
  locales/es/validation.json
  locales/fr/common.json
  locales/fr/validation.json
  locales/pt/common.json
  locales/pt/validation.json
  src/components/LanguageSelector/index.tsx
  src/components/LanguageSelector/util.ts
Labels: :recycle: Refatoração

#90 Botoes nao funcionais i73
  src/Templates/Dashboard/index.tsx
  src/components/Footer/index.tsx
  src/components/Profile/index.tsx
Labels: :recycle: Refatoração

#97 CRUD Assets#86
  src/App.tsx
  src/assets/check.svg
  src/components/Forms/CreateContract/index.tsx
  src/components/Forms/CreateContract/styles.ts
  src/components/Heading/styles.ts
  src/components/Heading/types.ts
  src/components/IconButton/index.tsx
  src/components/IconButton/styles.ts
  src/components/IconButton/types.ts
  src/components/Layout/index.tsx
  src/components/Layout/styles.ts
  src/components/RadioButton/styles.ts
  src/constants/navigation.ts
  src/features/AssetsCreation/index.tsx
  src/features/AssetsCreation/styles.ts
  src/features/AssetsCreation/types.ts
  src/features/HeaderContracts/index.tsx
  src/features/HeaderContracts/styles.ts
  src/features/ResourcesList/ResourcesListManager.tsx
  src/features/ResourcesList/styles.ts
  src/features/ResourcesType/ButtonDelete.tsx
  src/features/ResourcesType/ButtonEdit.tsx
  src/features/ResourcesType/ResourceTypesManager.tsx
  src/features/ResourcesType/styles.ts
  src/features/ResourcesType/types.ts
  src/pages/Contracts/CreatingAssets.tsx
  src/pages/Home/index.tsx
  src/routes/index.tsx
  src/templates/ContractsAssets/index.tsx
  src/templates/ContractsAssets/styles.ts
Labels: :sparkles: New feature
